In [1]:
# !pip install open3d

     ---------------------------------------- 62.2/62.2 MB 2.3 MB/s eta 0:00:00
     -------------------------------------- 138.3/138.3 kB 2.1 MB/s eta 0:00:00
     ---------------------------------------- 77.1/77.1 kB 1.4 MB/s eta 0:00:00
     ---------------------------------------- 10.4/10.4 MB 3.3 MB/s eta 0:00:00
     ---------------------------------------- 15.5/15.5 MB 3.5 MB/s eta 0:00:00
  Using cached Werkzeug-2.2.3-py3-none-any.whl (233 kB)
     -------------------------------------- 101.8/101.8 kB 6.1 MB/s eta 0:00:00
     ---------------------------------------- 2.3/2.3 MB 3.7 MB/s eta 0:00:00
     -------------------------------------- 215.0/215.0 kB 3.3 MB/s eta 0:00:00
  Attempting uninstall: widgetsnbextension
    Found existing installation: widgetsnbextension 3.6.0
    Uninstalling widgetsnbextension-3.6.0:
      Successfully uninstalled widgetsnbextension-3.6.0
  Attempting uninstall: werkzeug
    Found existing installation: Werkzeug 2.3.2
    Uninstalling Werkzeug


[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## 1. Import Statements

In [9]:
import open3d as o3d
import numpy as np
import os
import sys

# Only needed for tutorial
sys.path.append('..')

import open3d.examples as o3dtut
# Change to True if you want to interact with the visualization windows
o3dtut.interactive = not 'CI' in os.environ

In [11]:
pcd = o3d.io.read_point_cloud('Clouds/fragment.ply')
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

PointCloud with 196133 points.
[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation 